accueil:
  path: /
  controller: App\Controller\AccueilController::index

seConnecterVisiteur:
  path: /visiteur
  controller: App\Controller\ConnexionVisiteurController::index

consulterFrais:
  path: /visiteur/consulterFrais
  controller: App\Controller\ConsulterFraisController::index

afficherFicheFrais:
  path: /visiteur/consulterFrais/afficherFicheFrais
  controller: App\Controller\AfficherFicheFraisController::index