<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLrCCIGU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLrCCIGU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLrCCIGU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLrCCIGU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLrCCIGU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LrCCIGU',
    'container.build_id' => '2e1a2d88',
    'container.build_time' => 1600530384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLrCCIGU');
