<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4JVBwbd\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4JVBwbd/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4JVBwbd.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4JVBwbd\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4JVBwbd\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4JVBwbd',
    'container.build_id' => '553ee685',
    'container.build_time' => 1601557517,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4JVBwbd');
