<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDWfhpSb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDWfhpSb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDWfhpSb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDWfhpSb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDWfhpSb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DWfhpSb',
    'container.build_id' => 'a6214048',
    'container.build_time' => 1601210943,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDWfhpSb');
